name: Create ZIP File

on:
  push:
    branches:
      - main

jobs:
  zip-repository:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create ZIP File
        run: |
          # Change to repository directory
          cd $GITHUB_WORKSPACE/spring-initializer-defaults
          # Create zip with contents directly (no parent directory)
          zip -r spring-initializer-defaults.zip . -x '.git/*' '.github/*'
          # Move zip file back to workspace
          mv ../spring-initializer-defaults.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-initializer-defaults.zip
          path: spring-initializer-defaults.zip
